### ISSUE TITLE
[Domain Model] SpamTerms.term

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP8Entrega#10]
Debería ser un único String y notBlank. De la manera mencionada habría muchas entradas en la Tabla SpamTerms lo cual representaría muchos terminos. Como está representado en el UML quiere decir que la tabla tendría una única entrada que contendría la lista de términos

**Comment by ManuelLR** [comment]
En el caso de quedarse como está representado en el uml la variable debería llamarse terms y no term

**Comment by CeuxDruman** [comment]
mmm pues no tengo muy claro si una clase aislada representa 1 solo objeto o 0..\* (puesto que no está relacionada con nada), desde luego en supermarket pusimos la customizationInfo y exchangeRate como si fueran varios.

Lo cambio entonces y lo dejo como term String NotBlank. @ManuelLR

**Comment by ManuelLR** [comment]
Vale, no tocaré nada hasta que estos cambios los hagas sobre la rama develop en lugar de la master ya que donde hiciste los cambios se van a pisar con los que ya corrigió @guillermo-ag-95

**Comment by CeuxDruman** [comment]
@ManuelLR Corregido en Develop.

**Comment by ManuelLR** [comment]
Perfecto, todo listo
