### ISSUE TITLE
[Domain Model] SpamTerms -> SpamTerm

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP8Entrega#11]
Debería de llamarse en singular igual que el resto, no?

**Comment by guillermo-ag-95** [comment]
ATENCIÓN: LOS CAMBIOS EFECTUADOS SÓLO AFECTAN AL DOMAIN MODEL, NO HE TOCADO EL MODELO JAVA.

Domain Model modificado:
- Sustituido "SpamTerms" por "SpamTerm".

Cuando los demás miembros creáis que debemos cerrar este issue, cerradlo. Yo no he querido hacerlo todavía por la Milestone "Don't Close" de Manolo.
Recomiendo cerrarlo cuando también esté modificado el Modelo Java.

**Comment by ManuelLR** [comment]
Cambiado en el modelo de dominio
