### ISSUE TITLE
[Domain Model] Comment.moment ¿{Past}?

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP8Entrega#14]

**Comment by CeuxDruman** [comment]
@ManuelLR Al igual que la Issue #17 no hace falta tocar nada. No cierro por si acaso lo habías cambiado en el Modelo Java.

**Comment by CeuxDruman** [comment]
@ManuelLR Acabo de ver que has puesto el Past al menos en este caso, para que lo corrijas cuando puedas.

**Comment by ManuelLR** [comment]
Cambiado por NotNull
