### ISSUE TITLE
[Domain Model] Message.sentMoment ¿{Past}?

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP8Entrega#17]

**Comment by CeuxDruman** [comment]
No debe tener Past puesto que puede ser la hora y fecha actual (Present) sin ningún problema. Míralo como el placementMoment de las Order del supermarket, o como el mismo dato que no lo teníamos puesto, en ambos sitios es el mismo concepto.

Una opción viable sería ponerle past y en el servicio restarle 100 ms al Date a la hora de crearlo para que cumple con el Past, así lo comprobamos expresamente, aunque siendo esa fecha puesta automáticamente por el sistema (sin que pueda tocarla el usuario) no hay problema.

**Comment by ManuelLR** [comment]
Es que deberíamos de haberlo puesto en la otra entrega como la segunda opción que tu has comentado. Pero valorando lo que dices (la hora la pondrá el sistema y no el usuario) no es necesario ponerlo en Past a pesar de que sería lo lógico.

Listo
