### ISSUE TITLE
[Domain Model] Cambios pendientes de aplicar en la rama correcta

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP8Entrega#18]
Estos son los cambios que **ya** están **realizados** y no deben de realizarse nuevamente:
- #2 
- #7 
- #11

Estos son los cambios que debes **volver a realizar** en la rama correcta (parte de la Develop):
- #10
- #5

Estos son los **cambios** o discusiones **pendientes**:
- #13 
- #14 
- #15

**Comment by ManuelLR** [comment]
Te explico, la manera de realizar los cambios de manera cómoda será que trabajes directamente sobre Develop. Una vez que hayas hechos los cambios y el push comprueba que todo lo que cambiaste en master (en el commit @6fcf488ee6b68a814ad35d9c6df10f65b58769f1) está aplicado a la rama Develop. 

Después me avisas porque borraré el commit que hiciste sobre master y ya la rama Carlos podrás tenerla en Develop.

Suerte ! !

**Comment by CeuxDruman** [comment]
Resuelto.
