### ISSUE TITLE
modelo astah -> authority....¿clerk?

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP8Entrega#2]

**Comment by guillermo-ag-95** [comment]
ATENCIÓN: LOS CAMBIOS EFECTUADOS SÓLO AFECTAN AL DOMAIN MODEL, NO HE TOCADO EL MODELO JAVA.

Domain Model modificado:
- Sustituido "CONSUMER: String = "CONSUMER"" por "CUSTOMER: String = "CUSTOMER"".
- Eliminado el rol de CLERK de la entidad Authority.

Cuando los demás miembros creáis que debemos cerrar este issue, cerradlo. Yo no he querido hacerlo todavía por la Milestone "Don't Close" de Manolo.
Recomiendo cerrarlo cuando también esté modificado el Modelo Java.

**Comment by ManuelLR** [comment]
Modificado en el modelo Java
