### ISSUE TITLE
Comment.java > Line 52 > @Valid

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP8Entrega#28]
El @Valid se pone sólo para clases que se definan nuevas (como Item, Order, Gym, etc...) y no se pone para clases "predefinidas" de Java, como es el caso.

**Comment by ManuelLR** [comment]
Pregunta, donde has leído eso?
Yo tengo entendido que el "@Valid" es para validar constantemente ciertos datos y ahí hay un Range que necesita ser validado constantemente.
Ya me cuentas.
https://github.com/DPIRPSG/DP8Entrega/blame/Develop/WorkSpace/Acme-Six-Pack/src/main/java/domain/Comment.java#L52

**Comment by CeuxDruman** [comment]
En la teoría y en clase se explicó. No hay que ponerlo en tipos como int, Integer, Date, Boolean (vamos, tipos de Java) porque Java ya hace la validación por sí mismo. Las clases que nosotros creamos son las que necesitan de validación explícita.
