### ISSUE TITLE
En Booking...

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP8Entrega#3]
Hace falta el denied?
En caso de hacer falta... No se podría poner el conjunto aproved, denied y canceled como el Authority?

**Comment by CeuxDruman** [comment]
Sí, lo vimos necesario al leer todos los requisitos y querys. (Si no sería complejo saber si una reserva todavía no ha sido aceptada ni denegada, p.e.)

No se podría hacer de esa manera puesto que: 1. Es un valor cambiante, no fijo. 2. Por una parte una reserva puede estar aceptada o denegada, pero a la vez haber sido cancelada o no por un admin.

**Comment by ManuelLR** [comment]
Tras darle varios días vueltas y ver que los boolean siempre deben estar rellenos creo que la solución actual no es la mejor pero si la que menos problemas nos dará.
Conclusión: **Mejor dejarlo como está**
