### ISSUE TITLE
[Domain Model] Asociación Comment-Gym & Comment-Service 

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP8Entrega#5]
Según 22.1.
Write a comment and associate it with a gym **OR** a service

**Comment by CeuxDruman** [comment]
@ManuelLR Lo se, es lo que hablamos en clase (no se si fue cuando no estabas) de que había que preguntar si se puede poner la puerta XOR (como dimos en IR) que es el caso exacto.

Ante la duda de momento **lo pondremos con relaciones 0..1 en vez de 1 tanto con Gym como con Service** y controlaremos manualmente que 1 comentario sólo se pueda escribir a un Gym o un Service.

**Comment by CeuxDruman** [comment]
Corregido y añadida nota aclaratoria ante la imposibilidad de ponerlo técnicamente (a espera de que podamos o no usar la XOR): "A Comment can just be assigned to a Gym or a Service"

**Comment by ManuelLR** [comment]
Vale, no tocaré nada hasta que estos cambios los hagas sobre la rama develop en lugar de la master ya que donde hiciste los cambios se van a pisar con los que ya corrigió @guillermo-ag-95

**Comment by CeuxDruman** [comment]
@ManuelLR Corregido en Develop.

**Comment by ManuelLR** [comment]
A preguntar en clase

**Comment by CeuxDruman** [comment]
Esto ya fue preguntado, confirmado y resuelto.
