### ISSUE TITLE
Cambiar Consumer por Customer

### ISSUE THREAD

**Issue by guillermo-ag-95** [DPIRPSG/DP8Entrega#6]
En el CM y DM hay que modificar eso de la entidad Authority.

**Comment by guillermo-ag-95** [comment]
https://github.com/DPIRPSG/DP8Entrega/issues/2

**Comment by ManuelLR** [comment]
Comprobar que está cambiado en el código

**Comment by ManuelLR** [comment]
Como tu bien has dicho, cerrado en el #2 , corregido en el @a042a240e4b5ee27728a9e316747cc0fce2d105c
