### ISSUE TITLE
¡Collections en singular en vez de plural!

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP8Entrega#65]
En los modelos Java (y por lo tanto en todo el resto del proyecto) están mal puestos los nombres de las collection en algunos casos. Así pues, por ejemplo, un Customer que tiene varios bookings la collection se llama booking.

Hay que corregirlos todos del modelo java y de todo lo que lleve por delante (incluídas querys y quizá populate en los que no se hará notar el error en rojo).

**Comment by ManuelLR** [comment]
ACLARARSE ! ! ! ! ! !
Que hago @CeuxDruman y @migrodcab

**Comment by ManuelLR** [comment]
Solved
