### ISSUE TITLE
En Service picture->pictures

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP8Entrega#7]

**Comment by guillermo-ag-95** [comment]
ATENCIÓN: LOS CAMBIOS EFECTUADOS SÓLO AFECTAN AL DOMAIN MODEL, NO HE TOCADO EL MODELO JAVA.

Domain Model modificado:
- En la entidad Service, el atributo "picture" ha pasado a llamarse "pictures". Si no creéis que se tenga que poner en plural por alguna razón, en el PDF del L02, en la página 24, hay un ejemplo de atributo con plural cómo el que nosotros tenemos.

Cuando los demás miembros creáis que debemos cerrar este issue, cerradlo. Yo no he querido hacerlo todavía por la Milestone "Don't Close" de Manolo.
Recomiendo cerrarlo cuando también esté modificado el Modelo Java.

**Comment by ManuelLR** [comment]
Corregido en el Código del Modelo de Dominio
